languageCode = "de"
baseurl = "https://www.wetterhexen.com"
title = "Die Wetterhexen"
theme = "wetterhexen"

[author]
  name = "Die Wetterhexen"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Gelebte Volksmusik aus dem Alpenraum"
  Author = "Die Wetterhexen"
  email = "diewetterhexen@gmail.com"
# Ganalytics = "XX-00000000-0"

[[menu.main]]
  name = "Wetterhexen"
  url = "/"
  identifier = "home"
  weight = 1
[[menu.main]]
  name = "Das sind wir"
  url = "/wir/"
  identifier = "wir"
  weight = 2
[[menu.main]]
  name = "Musik"
  url = "/musik/"
  identifier = "musik"
  weight = 3
[[menu.main]]
  name = "Termine"
  url = "/termine/"
  identifier = "termine"
  weight = 4
[[menu.main]]
  name = "Projekte"
  url = "/projekte/"
  identifier = "projekte"
  weight = 5
[[menu.main]]
  name = "Kontakt"
  url = "/kontakt/"
  identifier = "kontakt"
  weight = 6
