languageCode = "de-de"
baseurl = "http://wetterhexen.com"
title = "Die Wetterhexen"
theme = "startbootstrap-clean-blog"

[author]
  name = "Die Wetterhexen"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Gelebte Volksmusik aus dem Alpenraum"
  Author = "Die Wetterhexen"
  email = "sagichnicht@example.com"
# Ganalytics = "XX-00000000-0"

#[[params.social]]
#  title = "twitter"
#  url = "https://twitter.com/humboldtux"
#[[params.social]]
#  title = "github"
#  url = "https://github.com/humboldtux"
#[[params.social]]
#  title = "facebook"
#  url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
